services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:7.0
    platform: linux/x86_64
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replica
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    ports:
      - '27017:27017'
    networks:
      - laptop-system
    volumes:
      - ./mongo_vol:/bitnami/mongodb

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:7.0
    platform: linux/x86_64
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replica
      - EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1
    ports:
      - '30001:27017'
    networks:
      - laptop-system

  
  kestra:
    image: kestra/kestra:latest
    command: server local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - 8080:8080

  

networks:
  laptop-system:
    name: laptop-system