version: '3.8'

services:
  scrapyd:
    build:
      context: .
      dockerfile: dockerfile.scrapyd
    depends_on:
      - scrapy_spider
    networks:
      - sdsp-common-services

  scrapy_spider:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - sdsp-common-services
    volumes:
      - .:/app
    ports:
      - "6800:6800"
    environment:
      - SCRAPY_PROJECT=crawler_app
    restart: always

  scrape:
    build:
      context: ./scrape
      dockerfile: dockerfile
    networks:
      - sdsp-common-services
    ports:
      - "8000:8000"

networks:
  sdsp-common-services:
    name: sdsp-common-services