version: '3.8'

services:
  scrapyd:
    build:
      context: .
      dockerfile: dockerfile.scrapyd
    depends_on:
      - scrapy_spider
    networks:
      - laptop-system

  scrapy_spider:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - laptop-system
    volumes:
      - .:/app
    ports:
      - "6800:6800"
    environment:
      - SCRAPY_PROJECT=crawler_app
    restart: always

networks:
  laptop-system:
    name: laptop-system
    external: true