FROM python:3.11.7-slim-bullseye

WORKDIR /app

COPY . .

RUN apt-get update
RUN apt-get install libpq-dev -y python-dev -y gcc git -y

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]